language: python

python:
  - "3.7"

env:
  - AWS_SECRET_ACCESS_KEY=fake_key AWS_ACCESS_KEY_ID=fake_id AWS_DEFAULT_REGION=eu-west-1

before_install:
  - pip install pytest pytest-cov
  - pip install coveralls

install:
  - cd $TRAVIS_BUILD_DIR/serverless && pip install -r requirements.txt
  
script:
  -  cd $TRAVIS_BUILD_DIR/serverless && coverage run --source ./serverless -m unittest

after_success:
  - coveralls