language: python

python:
  - "3.7"

env:
  - AWS_SECRET_ACCESS_KEY=fake_key AWS_ACCESS_KEY_ID=fake_id region=eu-west-1


install:
  - cd $TRAVIS_BUILD_DIR/serverless && pip install -r requirements.txt
  
script:
  -  cd $TRAVIS_BUILD_DIR/serverless && python -m unittest

after_success:
  - coveralls