version: '3.1'

services:
    dynamolocal:
        image: amazon/dynamodb-local:latest
        volumes:
            - ./my-dynamodb-data:/home/dynamodblocal/data
        ports:
            - 8000:8000
        command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"

    dynamoplus-local:
        build: .
        environment:
            AWS_ACCESS_KEY_ID: foo
            AWS_SECRET_ACCESS_KEY: bar
            DYNAMODB_HOST: http://dynamolocal
            DYNAMODB_PORT: 8000
            ROOT_PASSWORD: 12345
            SERVICE_NAME: e2e-tests
        volumes:
            - ./serverless/dynamoplus:/app/dynamoplus/serverless/dynamoplus
            - ./serverless/aws:/app/dynamoplus/serverless/aws
            - ./serverless/custom:/app/dynamoplus/serverless/custom
        ports:
            - 3000:3000
