version: '3.9'

services:
    dynamoplus-deploy:
        build:
            context: .
            dockerfile: deploy.Dockerfile
        environment:
            AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
            ENVIRONMENT: develop
            ROOT_PASSWORD: 12345
            SERVICE_NAME: dynamoplus-develop