version = 0.1
[default.deploy.parameters]
stack_name = "dynamoplus-dev"
resolve_s3 = true
s3_prefix = "dynamoplus-dev"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"Dev\""
image_repositories = []
