on:
  push:
    branches:
      - develop
name: Deploy develop branch
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@develop
    - name: npm install
      uses: actions/npm@develop
      with:
        args: install
    - name: serverless deploy
      uses: serverless/github-action@develop
      with:
        args: deploy
      working-directory: ./serverless
      env:
        # SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        # or if using AWS creds directly
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}