# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Integration tests

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Checkout SDK
      uses: actions/checkout@v2
      with:
        repository: antessio/dynamoplus-java-sdk
        path: dynamoplus-java-sdk
    - name: Install sdk
      run: mvn -B clean install --file dynamoplus-java-sdk/pom.xml

    - name: Checkout main project
      uses: actions/checkout@v2
    - name: List $GITHUB_WORKSPACE
      run: ls -lart
    - name: Running DynamoDB Local
      run: docker-compose -f docker-compose-localhost.yml up -d
    - uses: actions/checkout@master
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ./serverless
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: install sls
      run: npm install -g serverless
    - name: install dependencies
      run: npm install
      working-directory: ./serverless
    - name: run offline sls
      run: sls offline --stage=local
      working-directory: ./serverless
    - name: Wait for server up
      run: ./scripts/wait-for.sh http://localhost:3000/system/info 10 3
    - name: Creating tables
      run: ./scripts/create-tables.sh
    - name: Checkout e2e tests
      uses: actions/checkout@v2
      with:
        repository: antessio/dynamoplus-e2e-tests
        path: dynamoplus-e2e-tests
    - name: Running e2e tests on localhost
      run: mvn -B clean test -DrunSuite=**/SlowTestSuite.class --file dynamoplus-e2e-tests/pom.xml

