# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Integration tests

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build-dependencies:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Checkout SDK
      uses: actions/checkout@v2
      with:
        repository: antessio/dynamoplus-java-sdk
        path: dynamoplus-java-sdk
    - name: Install sdk
      run: mvn -B clean install --file dynamoplus-java-sdk/pom.xml
  running-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main project
        uses: actions/checkout@v2
      - name: List workspace
        run: ls -lart $GITHUB_WORKSPACE
      - name: Running localhost environment
        run: docker-compose -f docker-compose-localhost.yml up -d
      - name: Checkout e2e tests
        uses: actions/checkout@v2
        with:
          repository: antessio/dynamoplus-e2e-tests
          path: dynamoplus-e2e-tests
      - name: Running e2e tests on localhost
        run: mvn -B clean test --file dynamoplus-e2e-tests/pom.xml
  shutting-down-containers:
    runs-on: ubuntu-latest
      steps:
      - name: Shutting down docker containers
        run: docker-compose -f docker-compose-localhost.yml kill
