# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Integration tests

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Checkout SDK
      uses: actions/checkout@v2
      with:
        repository: antessio/dynamoplus-java-sdk
        path: dynamoplus-java-sdk
        ref: v0.5
    - name: Install sdk
      run: mvn -B clean install --file dynamoplus-java-sdk/pom.xml

    - name: Checkout main project
      uses: actions/checkout@v2
    - name: List $GITHUB_WORKSPACE
      run: ls -lart
    - name: Running DynamoPlus locally
      run: docker-compose -f docker-compose-localhost.yml up -d
    - name: Wait for server up
      run: ./github_actions_scripts/wait-for.sh http://localhost:3000/system/info 10 3
    - name: Creating tables
      run: ./github_actions_scripts/create-tables.sh
    - name: The job has failed
      if: ${{ failure() }}
      run: docker-compose -f docker-compose-localhost.yml logs
    - name: Checkout e2e tests
      uses: actions/checkout@v2
      with:
        repository: antessio/dynamoplus-e2e-tests
        path: dynamoplus-e2e-tests
        ref: v0.5
    - name: Running e2e tests on localhost
      run: mvn -B clean test -DrunSuite=**/TestSuite.class --file dynamoplus-e2e-tests/pom.xml
    - name: Shutting down DynamoPlus locally
      run: docker-compose -f docker-compose-localhost.yml kill
    - name: Removing containers
      run: docker-compose -f docker-compose-localhost.yml kill

