# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Integration tests

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Checkout SDK
      uses: actions/checkout@v2
      with:
        repository: antessio/dynamoplus-java-sdk
        path: dynamoplus-java-sdk
    - name: Install sdk
      run: mvn -B clean install --file dynamoplus-java-sdk/pom.xml

    - name: Checkout main project
      uses: actions/checkout@v2
    - name: List $GITHUB_WORKSPACE
      run: ls -lart
    - name: Running DynamoDB Local
      run: docker-compose -f docker-compose-localhost.yml up -d
    - uses: actions/checkout@master
    - name: npm install
      uses: actions/npm@master
    - name: install dependencies
      run: npm install --prefix ./serverless
    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: offline --stage=local
          # or if using AWS creds directly
          # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}